# Generated by Django 3.2.7 on 2022-11-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Products',
        ),
    ]
