# Generated by Django 3.2.7 on 2022-11-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='Battery',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='Flight_distance',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='Flight_time',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='weight',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
