# Generated by Django 3.2.7 on 2022-11-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
