# Generated by Django 3.2.7 on 2022-11-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0003_uav_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='uavAdmin',
            fields=[
                ('uav_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uav.uav')),
            ],
            bases=('uav.uav',),
        ),
    ]
